### ISSUE TITLE
Migrations and dark/light deployments

### ISSUE THREAD

**Issue by kardan** [akvo/akvo-lumen#1266]
# Context
We have switched to using dark/light deployments. In our case, this means that we will run two versions of the same Lumen application against the same database. The schema for the newer (dark) version of the app will be applied to the database. This means that the older version of the application needs to be able to handle the newer database.

# Problem or idea
Test case:
Add a new migration in a branch. Kill docker-compose and checkout develop. Then issue docker-compose up (without rebuilding containers). This means that we are in a place where an older version of the app needs to run against a newer database, as with dark/light deployments.

```shell
backend_1    | Starting BackEnd ...
backend_1    | 07:45:43.447 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariCP pool HikariPool-0 is starting.
backend_1    | 07:45:45.520 [main] INFO  akvo.lumen.component.keycloak - Successfully got openid-config from provider.
backend_1    | 07:45:45.530 [main] INFO  akvo.lumen.component.emailer - Using std out emailer
backend_1    | 07:45:46.078 [main] INFO  org.xnio - XNIO version 3.3.6.Final
backend_1    | 07:45:46.221 [main] INFO  org.xnio.nio - XNIO NIO Implementation Version 3.3.6.Final
backend_1    | 07:45:46.712 [main] INFO  org.projectodd.wunderboss.web.Web - Registered web context /
backend_1    | Exception in thread "main" java.lang.Exception: Conflict! Expected  but 013-migration-test was applied., compiling:(/tmp/form-init2459906767478846502.clj:1:73)
backend_1    |  at clojure.lang.Compiler.load(Compiler.java:7526)
backend_1    |  at clojure.lang.Compiler.loadFile(Compiler.java:7452)
backend_1    |  at clojure.main$load_script.invokeStatic(main.clj:278)
backend_1    |  at clojure.main$init_opt.invokeStatic(main.clj:280)
backend_1    |  at clojure.main$init_opt.invoke(main.clj:280)
backend_1    |  at clojure.main$initialize.invokeStatic(main.clj:311)
backend_1    |  at clojure.main$null_opt.invokeStatic(main.clj:345)
backend_1    |  at clojure.main$null_opt.invoke(main.clj:342)
backend_1    |  at clojure.main$main.invokeStatic(main.clj:424)
backend_1    |  at clojure.main$main.doInvoke(main.clj:387)
backend_1    |  at clojure.lang.RestFn.applyTo(RestFn.java:137)
backend_1    |  at clojure.lang.Var.applyTo(Var.java:702)
backend_1    |  at clojure.main.main(main.java:37)
backend_1    | Caused by: java.lang.Exception: Conflict! Expected  but 013-migration-test was applied.
backend_1    |  at ragtime.strategy$raise_error.invokeStatic(strategy.clj:39)
backend_1    |  at ragtime.strategy$raise_error.invoke(strategy.clj:31)
backend_1    |  at ragtime.core$migrate_all.invokeStatic(core.clj:44)
backend_1    |  at ragtime.core$migrate_all.invoke(core.clj:32)
backend_1    |  at ragtime.repl$migrate.invokeStatic(repl.clj:49)
backend_1    |  at ragtime.repl$migrate.invoke(repl.clj:34)
backend_1    |  at akvo.lumen.migrate$do_migrate.invokeStatic(migrate.clj:19)
backend_1    |  at akvo.lumen.migrate$do_migrate.invoke(migrate.clj:18)
backend_1    |  at akvo.lumen.migrate$migrate.invokeStatic(migrate.clj:51)
backend_1    |  at akvo.lumen.migrate$migrate.invoke(migrate.clj:41)
backend_1    |  at akvo.lumen.migrate$migrate.invokeStatic(migrate.clj:43)
backend_1    |  at akvo.lumen.migrate$migrate.invoke(migrate.clj:41)
backend_1    |  at dev$migrate.invokeStatic(dev.clj:63)
backend_1    |  at dev$migrate.invoke(dev.clj:62)
backend_1    |  at dev$migrate_and_seed.invokeStatic(dev.clj:66)
backend_1    |  at dev$migrate_and_seed.invoke(dev.clj:65)
backend_1    |  at dev$eval28621.invokeStatic(form-init2459906767478846502.clj:1)
backend_1    |  at dev$eval28621.invoke(form-init2459906767478846502.clj:1)
backend_1    |  at clojure.lang.Compiler.eval(Compiler.java:7062)
backend_1    |  at clojure.lang.Compiler.eval(Compiler.java:7052)
backend_1    |  at clojure.lang.Compiler.eval(Compiler.java:7052)
backend_1    |  at clojure.lang.Compiler.eval(Compiler.java:7051)
backend_1    |  at clojure.lang.Compiler.load(Compiler.java:7514)
backend_1    |  ... 12 more
```

On startup (https://github.com/akvo/akvo-lumen/blob/develop/backend/src/akvo/lumen/main.clj#L19) we run migrations for all tenants, this is what's failing. 

# Solution or next step
Possible paths:
-  Use another migration strategy (https://github.com/weavejester/ragtime/blob/master/core/src/ragtime/strategy.clj) 
- Run the entire Ragtime migration machinery within a try/catch block.
- Investigate other migration solutions

**Comment by kardan** [comment]
@dlebrero @iperdomo thoughts?

**Comment by dlebrero** [comment]
Instead of ignoring any error, the live deployment has to expect for some future migrations to be in the DB. 

So if the deployment knows about migrations A,B and C, but the DB contains migrations A, B, C and D, that is expected.

If a deployment knows about migrations A, B and C, but the DB contains migrations A,B and X, then this is unexpected and Lumen should refuse to start.

**Comment by kardan** [comment]
Agree with you @dlebrero. Didn't mean that you had to implement the strategy solution. Just did the fastest things possible to show something on my initial attempt. Your strategy implementation is better.

**Comment by dlebrero** [comment]
I feel responsible for anything blue/green related, plus I already had started the implementation before you even open this issue :P
